'use strict';
/**
 * pre-receive hook for the cross-ref consumed-grant ledger (roadmap 1187).
 *
 * WHY IT EXISTS. `receive.denyDeletes` does NOT cover refs/coderifts/consumed/* —
 * measured 2026-08-29 on git 2.50.1: deleting refs/heads/probe was refused
 * (`deletion prohibited`), deleting a ledger ref SUCCEEDED. The setting guards
 * branches, not arbitrary namespaces. Deleting a ledger ref re-opens exactly the
 * cross-ref replay the ledger closes, so the namespace needs its own rule.
 *
 * WHAT IT REFUSES, and why each case:
 *   · DELETE (new = all-zeros) — erases a consumed claim; the grant becomes
 *     replayable. This is the vector the whole slice exists to close.
 *   · OVERWRITE (old != all-zeros) — a claim is create-only by construction
 *     (git-atomic.js writes it with the all-zeros expected-old). Repointing an
 *     existing claim is not a legitimate operation; permitting it would let a
 *     claim be laundered rather than deleted.
 *   · CREATE (old = all-zeros, new = real sha) is PERMITTED — that is a new
 *     grant being consumed, the normal path.
 * Anything outside refs/coderifts/consumed/ is untouched: branch pushes and
 * deletions keep following the repository's own config.
 *
 * WHAT IT DOES NOT DO — and this is the honest boundary, not a footnote:
 *   It closes the PUSH-level deletion vector, nothing more. An actor with
 *   filesystem access to the bare repository can `rm` a ref or edit packed-refs
 *   and the hook never runs — pre-receive is invoked by git-receive-pack, and a
 *   direct write does not go through it. The trusted-storage assumption stated in
 *   git-atomic.js is unchanged. This hook does NOT make the ledger tamper-proof.
 *
 *   It also protects nothing until it is INSTALLED on the bare repository that
 *   serves pushes. An uninstalled hook is a file, not a control.
 *
 * POSIX sh, deliberately. The hook runs on the GIT SERVER, which may be any host
 * with git on it — a node runtime there is an assumption we cannot make and do
 * not need. No dependencies, no interpreter beyond /bin/sh.
 */

const fs = require('node:fs');
const path = require('node:path');

const { LEDGER_PREFIX, MUST_NOT_EXIST } = require('./git-atomic');

/**
 * THE ONE SOURCE for the hook text. demo/hooks/pre-receive is generated from
 * this and pinned by a drift test — two hand-maintained copies would disagree
 * the first time one is edited.
 */
const PRE_RECEIVE_HOOK = `#!/bin/sh
# CodeRifts consumed-grant ledger protection (roadmap 1187).
#
# Refuses DELETE and OVERWRITE of ${LEDGER_PREFIX}/*; permits CREATE.
# Everything outside that namespace passes through untouched.
#
# Closes the PUSH-level deletion vector only. A writer with filesystem access to
# this repository bypasses receive-pack entirely and this hook never runs —
# trusted storage remains an assumption, not something a hook can enforce.
#
# Generated by demo/src/ledger-hook.js — edit there, not here.

ZERO='${MUST_NOT_EXIST}'
LEDGER='${LEDGER_PREFIX}/'
status=0

# Read every triple before exiting, so one push reports all of its problems.
while read -r old new ref; do
  case "$ref" in
    "$LEDGER"*)
      if [ "$new" = "$ZERO" ]; then
        echo "remote: REFUSED $ref — deleting a consumed-grant claim would re-open replay" >&2
        status=1
      elif [ "$old" != "$ZERO" ]; then
        echo "remote: REFUSED $ref — a consumed-grant claim is create-only; overwriting it launders the claim" >&2
        status=1
      fi
      ;;
  esac
done

if [ "$status" -ne 0 ]; then
  echo "remote: the consumed-grant ledger is append-only. Nothing was pushed." >&2
fi
exit "$status"
`;

/**
 * Install the hook into a bare repository.
 *
 * EXPLICIT, never automatic. Writing a hook into someone's repository as a side
 * effect of starting a server would be a surprising mutation of a thing the
 * operator owns, and it would silently overwrite a hook they wrote themselves.
 *
 * @param {string} bareRepoDir  path to the bare repo (the one that serves pushes)
 * @param {object} [o]
 * @param {boolean} [o.force]   overwrite an existing pre-receive hook
 * @returns {{ installed: boolean, path: string, reason?: string }}
 */
function installLedgerHook(bareRepoDir, { force = false } = {}) {
  const hooksDir = path.join(bareRepoDir, 'hooks');
  const dest = path.join(hooksDir, 'pre-receive');
  if (!fs.existsSync(bareRepoDir)) {
    return { installed: false, path: dest, reason: 'repo_not_found' };
  }
  if (fs.existsSync(dest) && !force) {
    const current = fs.readFileSync(dest, 'utf8');
    if (current === PRE_RECEIVE_HOOK) return { installed: true, path: dest, reason: 'already_current' };
    // Never clobber a hook we did not write. An operator's own pre-receive may be
    // doing something we know nothing about.
    return { installed: false, path: dest, reason: 'existing_hook_differs' };
  }
  fs.mkdirSync(hooksDir, { recursive: true });
  fs.writeFileSync(dest, PRE_RECEIVE_HOOK, { mode: 0o755 });
  fs.chmodSync(dest, 0o755);
  return { installed: true, path: dest };
}

/** Is the current hook text installed on this repo? Used by tests and operators. */
function ledgerHookInstalled(bareRepoDir) {
  const dest = path.join(bareRepoDir, 'hooks', 'pre-receive');
  try {
    return fs.readFileSync(dest, 'utf8') === PRE_RECEIVE_HOOK;
  } catch {
    return false;
  }
}

module.exports = { PRE_RECEIVE_HOOK, installLedgerHook, ledgerHookInstalled };
